# Generated by Django 4.2.7 on 2023-12-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='auth_method',
            field=models.CharField(default='E', max_length=50),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
