# Generated by Django 4.2.7 on 2023-12-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customusermodel_auth_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='google_profile_picture',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
