# Generated by Django 4.2.7 on 2023-12-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customusermodel_google_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
